version: "3.3"

services:
  zcs-dev:
    build:
      context: .
      dockerfile: Dockerfile-base
    image: zimbra/zcs-dev-base:8.8.4ga
    container_name: zcs-dev
    domainname: test
    hostname: zcs-dev
    networks:
      default:
        ipv4_address: 10.0.0.3
    ports:
      - "2222:22"
      - "7071:7071"
      - "8143:143"
      - "8443:443"
      - "8993:993"
      - "9998:9998"
      - "9999:9999"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
